<a href="https://colab.research.google.com/github/Yahayacs4u/Pytorch-Tutorial/blob/main/PYTORCH_BASIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import io
import torch

In [ ]:
#df = sns.load_dataset("iris")

In [5]:
tensor_a = torch.arange(10)

In [7]:
tensor_a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
tensor_b = torch.arange(10)

In [9]:
tensor_b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x = tensor_a+tensor_b
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
torch.add(tensor_a, tensor_b)


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
torch.mul(tensor_a, tensor_b)

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
torch.sub(tensor_a, tensor_b)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
torch.div(tensor_a, tensor_b)

tensor([nan, 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
y = torch.arange(2,3)

In [17]:
y

tensor([2])

In [18]:
tensor_a.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [2]:
my_list2 = [[1,2,3,4,5],[6,7,8,9,10]]

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
x = np.random.rand(3,3)
x

array([[0.30820368, 0.96916715, 0.53108951],
       [0.47319514, 0.0593679 , 0.43412268],
       [0.29675608, 0.53969344, 0.45901516]])

In [14]:
x.dtype

dtype('float64')

In [8]:
y = torch.randn(3,3)
y

tensor([[-0.7131, -1.7355,  0.6053],
        [-0.3003,  1.2458,  0.8586],
        [-0.6129,  0.0441, -1.2799]])

In [19]:
m2d = torch.tensor(x)
m2d

tensor([[0.3082, 0.9692, 0.5311],
        [0.4732, 0.0594, 0.4341],
        [0.2968, 0.5397, 0.4590]], dtype=torch.float64)

In [20]:
y3d = torch.randn(3,4,5)
y3d

tensor([[[ 0.3443,  0.7345,  0.6655, -1.0322, -0.3267],
         [ 0.3567,  1.6245,  0.0731,  0.9445,  1.2607],
         [-0.6350, -0.3375, -2.2440, -0.3834, -0.0845],
         [-2.3642,  0.2698, -1.8769,  1.5270, -1.1477]],

        [[ 0.2922,  0.0709, -0.2523,  2.0171,  1.4204],
         [-1.6318,  1.0510, -0.4792, -2.1780, -1.2241],
         [-0.5989,  0.4038, -0.2863,  0.1689,  0.9976],
         [ 2.7287,  0.3209, -1.5317,  0.3969,  0.7638]],

        [[-0.3964, -0.4505,  0.3682, -1.0775, -0.0480],
         [-0.8138, -0.6685,  0.8962, -1.2851,  1.4187],
         [ 0.4032,  1.5057,  1.9293,  0.4956, -1.3476],
         [-0.2142,  0.2325,  1.1354,  1.5803,  0.2129]]])

In [21]:
y4d = torch.randn(3,4,5,6)
y4d

tensor([[[[-1.3671e+00, -1.8073e+00, -1.1286e+00, -3.0065e-01, -7.1085e-01,
           -7.1462e-01],
          [-2.1305e-01, -1.7150e+00,  2.3608e-01, -6.7765e-01, -1.3709e-01,
           -1.0603e+00],
          [-4.4525e-01,  3.1416e-01,  5.6974e-01,  5.0206e-01,  5.9853e-01,
            2.1593e+00],
          [ 1.6853e+00, -5.6742e-02, -9.1324e-02, -2.0710e+00,  5.7839e-01,
           -6.3755e-01],
          [-1.8035e-01, -6.3724e-01, -1.4595e+00,  7.2395e-01,  6.7351e-02,
            1.5168e+00]],

         [[-4.3470e-01, -2.3461e-01,  3.8705e-01,  6.4313e-01, -1.0760e+00,
           -5.9943e-01],
          [-1.4436e+00,  5.0594e-01, -9.2169e-01, -8.8234e-01, -2.1194e-01,
           -2.9194e-01],
          [-2.2075e+00, -6.7606e-01,  1.2762e+00,  6.7822e-01,  4.2882e-01,
           -5.7163e-01],
          [ 4.9032e-01,  5.3625e-01, -6.6117e-01,  1.1019e+00, -1.9732e-01,
           -2.9900e-01],
          [ 1.0806e+00,  9.4703e-01, -5.9083e-01,  5.7441e-01, -1.5485e-01,
            2