<a href="https://colab.research.google.com/github/Yahayacs4u/Pytorch-Tutorial/blob/main/PYTORCH_BASIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import io
import torch

In [ ]:
#df = sns.load_dataset("iris")

In [ ]:
tensor_a = torch.arange(10)

In [ ]:
tensor_a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_b = torch.arange(10)

In [ ]:
tensor_b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = tensor_a+tensor_b
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
torch.add(tensor_a, tensor_b)


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
torch.mul(tensor_a, tensor_b)

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
torch.sub(tensor_a, tensor_b)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
torch.div(tensor_a, tensor_b)

tensor([nan, 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
y = torch.arange(2,3)

In [ ]:
y

tensor([2])

In [ ]:
tensor_a.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
my_list2 = [[1,2,3,4,5],[6,7,8,9,10]]

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
x = np.random.rand(3,3)
x

array([[0.30820368, 0.96916715, 0.53108951],
       [0.47319514, 0.0593679 , 0.43412268],
       [0.29675608, 0.53969344, 0.45901516]])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
y = torch.randn(3,3)
y

tensor([[-0.7131, -1.7355,  0.6053],
        [-0.3003,  1.2458,  0.8586],
        [-0.6129,  0.0441, -1.2799]])

In [ ]:
m2d = torch.tensor(x)
m2d

tensor([[0.3082, 0.9692, 0.5311],
        [0.4732, 0.0594, 0.4341],
        [0.2968, 0.5397, 0.4590]], dtype=torch.float64)

In [ ]:
y3d = torch.randn(3,4,5)
y3d

tensor([[[ 0.3443,  0.7345,  0.6655, -1.0322, -0.3267],
         [ 0.3567,  1.6245,  0.0731,  0.9445,  1.2607],
         [-0.6350, -0.3375, -2.2440, -0.3834, -0.0845],
         [-2.3642,  0.2698, -1.8769,  1.5270, -1.1477]],

        [[ 0.2922,  0.0709, -0.2523,  2.0171,  1.4204],
         [-1.6318,  1.0510, -0.4792, -2.1780, -1.2241],
         [-0.5989,  0.4038, -0.2863,  0.1689,  0.9976],
         [ 2.7287,  0.3209, -1.5317,  0.3969,  0.7638]],

        [[-0.3964, -0.4505,  0.3682, -1.0775, -0.0480],
         [-0.8138, -0.6685,  0.8962, -1.2851,  1.4187],
         [ 0.4032,  1.5057,  1.9293,  0.4956, -1.3476],
         [-0.2142,  0.2325,  1.1354,  1.5803,  0.2129]]])

In [14]:
#y4d = torch.randn(3,4,5,6)


In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [30]:
#create a model
class Model(nn.Module):
    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        super().__init__()
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        return x

In [31]:
torch.manual_seed(41)
model = Model()


In [2]:
import seaborn as sns
df = sns.load_dataset("iris")

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [5]:
df['species']= df['species'].map({'setosa':0, 'versicolor':1, 'virginica':2})

In [6]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [7]:
df.shape

(150, 5)

In [8]:
# Train test split
x = df.drop('species', axis=1).values
y = df['species'].values

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
# Train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=41)

In [12]:
# Convert x features to float tensors
import torch
x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)

In [13]:
# Convert y labels to tensors long
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, TensorDataset

# Set random seeds for reproducibility
torch.manual_seed(42)
torch.cuda.manual_seed(42)

# 1. Load and preprocess data
iris = load_iris()
X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

# Create datasets and dataloaders
train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

# 2. Define the model (using your provided architecture)
class IrisModel(nn.Module):
    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        super().__init__()
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        return x

# 3. Initialize model, loss, and optimizer
model = IrisModel()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# 4. Training loop
epochs = 100
for epoch in range(epochs):
    model.train()
    train_loss = 0.0

    for inputs, labels in train_loader:
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Print training progress
    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {train_loss/len(train_loader):.4f}')

# 5. Evaluation
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'\nTest Accuracy: {100 * correct / total:.2f}%')

# 6. Save model (optional)
torch.save(model.state_dict(), 'iris_model.pth')

Epoch [10/100], Loss: 0.2314
Epoch [20/100], Loss: 0.0969
Epoch [30/100], Loss: 0.0572
Epoch [40/100], Loss: 0.0530
Epoch [50/100], Loss: 0.0508
Epoch [60/100], Loss: 0.0547
Epoch [70/100], Loss: 0.0529
Epoch [80/100], Loss: 0.0455
Epoch [90/100], Loss: 0.0471
Epoch [100/100], Loss: 0.0434

Test Accuracy: 100.00%
